version: "3.9"

services:
# ----------------------- Scrapers / Bronze ingestion -----------------------
  biggie:
    build:
      context: .
      dockerfile: Dockerfile.pi 
    container_name: scraper_biggie
    volumes:
      - ~/docker-data/webscrapping-tesis:/app/scripts/bronze/outputs
      - ~/docker-data/webscrapping-tesis/logs:/app/logs
    command: >
      sh -c "python scripts/bronze/biggie.py > /app/logs/biggie.log 2>&1"
    restart: unless-stopped
    tty: true
    stdin_open: true

  real:
    build:
      context: .
      dockerfile: Dockerfile.pi
    container_name: scraper_real
    volumes:
      - ~/docker-data/webscrapping-tesis:/app/scripts/bronze/outputs
      - ~/docker-data/webscrapping-tesis/logs:/app/logs
    command: >
      sh -c "python scripts/bronze/real.py > /app/logs/real.log 2>&1"
    restart: unless-stopped
    tty: true
    stdin_open: true

  superseis:
    build:
      context: .
      dockerfile: Dockerfile.pi
    container_name: scraper_superseis
    volumes:
      - ~/docker-data/webscrapping-tesis:/app/scripts/bronze/outputs
      - ~/docker-data/webscrapping-tesis/logs:/app/logs
    command: >
      sh -c "python scripts/bronze/s6.py > /app/logs/s6.log 2>&1"
    restart: unless-stopped
    tty: true
    stdin_open: true

  stock:
    build:
      context: .
      dockerfile: Dockerfile.pi
    container_name: scraper_stock
    volumes:
      - ~/docker-data/webscrapping-tesis:/app/scripts/bronze/outputs
      - ~/docker-data/webscrapping-tesis/logs:/app/logs
    command: >
      sh -c "python scripts/bronze/stock.py > /app/logs/stock.log 2>&1"
    restart: unless-stopped
    tty: true
    stdin_open: true

  casa_rica:
    build:
      context: .
      dockerfile: Dockerfile.pi
    container_name: scraper_casa_rica
    volumes:
      - ~/docker-data/webscrapping-tesis:/app/scripts/bronze/outputs
      - ~/docker-data/webscrapping-tesis/logs:/app/logs
    command: >
      sh -c "python scripts/bronze/casa_rica.py > /app/logs/casa_rica.log 2>&1"
    restart: unless-stopped
    tty: true
    stdin_open: true

  monitor:
    build:
      context: .
      dockerfile: Dockerfile.pi
    container_name: monitor
    volumes:
      - /home/ivanspi/docker-data/webscrapping-tesis:/app/ingestions
      - /home/ivanspi/docker-data/webscrapping-tesis/logs:/app/logs
    environment:
      - INGESTIONS_DIR=/app/ingestions
      - LOGS_DIR=/app/logs
    command: >
      sh -c "python -u scripts/monitor.py 2>&1 | tee /app/logs/monitor.log"
    restart: unless-stopped

  postgres:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secure_password
      POSTGRES_DB: myapp
    ports:
      - "5432:5432" 
    volumes:
      - /home/ivanspi/docker-data/webscrapping-tesis/pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin_password
    ports:
      - "5050:80"
    depends_on:
      - postgres
    restart: unless-stopped

  silver:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: silver_loader
    command: >
      sh -c "
        echo '🚀 Iniciando ETL Silver...';
        python -u scripts/silver/bronze_to_silver_categories.py 2>&1 | tee /app/logs/bronze_to_silver_categories.log &&
        python -u scripts/silver/bronze_to_silver_products.py 2>&1 | tee /app/logs/bronze_to_silver_products.log
      "
    depends_on:
      - postgres
    environment:
      - BRONZE_PATH=/app/scripts/bronze/outputs
      - DB_DSN=host=postgres_db port=5432 dbname=myapp user=admin password=secure_password
      - MAPPINGS_CATEGORIES_FILE=/app/scripts/silver/categories_columns_mappings.json
      - MAPPINGS_PRODUCTS_FILE=/app/scripts/silver/products_columns_mappings.json
    volumes:
      - /home/ivanspi/docker-data/webscrapping-tesis:/app/scripts/bronze/outputs
      - /home/ivanspi/docker-data/webscrapping-tesis/logs:/app/logs

  silver_staging:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: silver_transformations
    command: >
      sh -c "
        echo '🚀 Iniciando transformaciones de Silver...';
        python -u scripts/silver/categories_transformations.py 2>&1 | tee /app/logs/categories_transformations.log &&
        python -u scripts/silver/products_transformations.py 2>&1 | tee /app/logs/products_transformations.log
      "
    depends_on:
      - postgres
    environment:
      - DB_DSN=host=postgres_db port=5432 dbname=myapp user=admin password=secure_password
    volumes:
      - /home/ivanspi/docker-data/webscrapping-tesis/logs:/app/logs

    #### GRAFANA ####

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=ellayel2025
    volumes:
      - /home/ivanspi/docker-data/webscrapping-tesis/grafana_data:/var/lib/grafana
    restart: unless-stopped